# Using official MySQL as a base image
FROM mysql:8.0.26

LABEL Author="Umesh Tyagi"

#ENV MYSQL_USER umesh
#ENV MYSQL_PASSWORD Umesh@123
#ENV MYSQL_DATABASE todo
#ENV MYSQL_ROOT_PASSWORD super@secret1

COPY scripts/ /docker-entrypoint-initdb.d/